# Enable privilage escalation , and tags (root, ibmsase, ibmsasc) in ansible tower before execution.

---
- hosts: localhost
  user: ansible
  #become: true
  #become_method: sudo
  #become_user: root   
  vars:
    - root_user: '^(root):([^:]*):'
    - ibmsase_user: '^(ibmsase):([^:]*):'
    - ibmsasc_user: '^(ibmsasc):([^:]*):'
    - encrypted_pass: "$6$NnVHJxuBZsjOoGO4$3nNF1m6VZtMcucqdGmlEK90LviCNYp9KZo.d36KdTGqRL1rpqSMKfW.Kj08MixRDn6tt1noPI5wNU6t5b1Q7y0" ##password for this is 111.
    - newvalue: '\g<1>:{{ encrypted_pass }}:'
  tasks:
    - name: replace old encrypted password with new for root user
      replace:
        path: /etc/shadow.bakk-20221005T111413 #### used backupfile
        regexp:  "{{ root_user }}" 
        replace: "{{ newvalue }}"
        backup: yes
      tags: [never, root]

    - name: replace old encrypted password with new for ibmsase user
      replace:
        path: /etc/shadow.bakk-20221005T111413 #### used backupfile
        regexp:  "{{ ibmsase_user }}"
        replace: "{{ newvalue }}"
        backup: yes
      tags: [never, ibmsase]

    - name: replace old encrypted password with new for ibmsasc user
      replace:
        path: /etc/shadow.bakk-20221005T111413 #### used backupfile
        regexp:  "{{ ibmsasc_user }}"
        replace: "{{ newvalue }}"
        backup: yes
      tags: [never, ibmsasc]
      
      
