---
- name: change root account password
  hosts: localhost
  vars_files:
    - vault_file.yml
  vars:
    account: "root"
    
  tasks:
    - name: changing password
      user:
        name: "{{account}}"
        state: present
        password: "{{accountpass|password_hash('sha512')}}"

  
