---
- name: change root account password
  become: true
  become_method: sudo
  become_user: root
  become_ask_pass: false
  hosts: all
  #vault-password-file: encrypt_code
  vars_files:
    - vault_file.yml
  tasks:
    - name: changing password
      user:
        name: root
        password: "{{accountpass|password_hash('sha512')}}"
      tags: [never, root]
      
    - name: changing password
      user:
        name: ibmsase
        password: "{{accountpass|password_hash('sha512')}}"
      tags: [never, ibmsase]
      
    - name: changing password
      user:
        name: ibmsasc
        password: "{{accountpass|password_hash('sha512')}}"
      tags: [never, ibmsasc]
  
