---
- name: change root account password
  hosts: all
  vars_files:
    - vault_file.yml
  ANSIBLE_VAULT_PASSWORD_FILE: encrypt_code
  tasks:
    - name: changing password
      user:
        name: root
        state: present
        password: "{{accountpass|password_hash('sha512')}}"
      tags: [never, root]
      
    - name: changing password
      user:
        name: ibmsase
        state: present
        password: "{{accountpass|password_hash('sha512')}}"
      tags: [never, ibmsase]
      
    - name: changing password
      user:
        name: ibmsasc
        state: present
        password: "{{accountpass|password_hash('sha512')}}"
      tags: [never, ibmsasc]
  
