---
- name: change root account password
  hosts: all
  vars_files:
    - vault_file.yml

  tasks:
    - name: changing password
      user:
        name: root
        state: present
        password: "{{accountpass|password_hash('sha512')}}"
      tags: root
      
    - name: changing password
      user:
        name: ibmsase
        state: present
        password: "{{accountpass|password_hash('sha512')}}"
      tags: ibmsase
      
    - name: changing password
      user:
        name: ibmsasc
        state: present
        password: "{{accountpass|password_hash('sha512')}}"
      tags: ibmsasc
  
